src/open_inwoner/api/urls.py
from django.urls import include, path

from drf_spectacular.views import SpectacularJSONAPIView, SpectacularRedocView
from rest_framework import routers

from .pdc.views import CategoryViewSet, ProductViewSet
from .search.views import AutocompleteView

app_name = "api"
router = routers.SimpleRouter()
router.register("categories", CategoryViewSet, basename="categories")
router.register("products", ProductViewSet, basename="products")


urlpatterns = [
    path(
        "schema/",
        SpectacularJSONAPIView.as_view(authentication_classes=[]),
        name="schema",
    ),
    path(
        "docs/",
        SpectacularRedocView.as_view(authentication_classes=[], url_name="api:schema"),
        name="docs",
    ),
    path(
        "search/autocomplete/", AutocompleteView.as_view(), name="search_autocomplete"
    ),
    path("", include(router.urls)),
]

src/open_inwoner/cms/products/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView

from open_inwoner.pdc.views import (
    CategoryDetailView,
    CategoryListView,
    ProductDetailView,
    ProductFinderView,
    ProductFormView,
    ProductLocationDetailView,
)
from open_inwoner.questionnaire.views import (
    QuestionnaireExportView,
    QuestionnaireResetView,
    QuestionnaireRootListView,
    QuestionnaireStepView,
)

app_name = "products"

urlpatterns = [
    path("ontdekken/", ProductFinderView.as_view(), name="product_finder"),
    path("questionnaire/reset", QuestionnaireResetView.as_view(), name="reset"),
    path("questionnaire/<str:slug>", QuestionnaireStepView.as_view(), name="root_step"),
    path(
        "questionnaire/<str:root_slug>/<str:slug>",
        QuestionnaireStepView.as_view(),
        name="descendent_step",
    ),
    path(
        "questionnaire/export/",
        QuestionnaireExportView.as_view(),
        name="questionnaire_export",
    ),
    path(
        "questionnaire/", QuestionnaireRootListView.as_view(), name="questionnaire_list"
    ),
    path(
        "locaties/<str:uuid>",
        ProductLocationDetailView.as_view(),
        name="location_detail",
    ),
    path(
        "producten/<str:slug>/formulier/",
        ProductFormView.as_view(),
        name="product_form",
    ),
    path(
        # Required to handle dynamic URL-paths appended by Open Forms.
        "producten/<str:slug>/formulier/<path:rest>",
        ProductFormView.as_view(),
        name="product_form",
    ),
    path(
        "producten/<str:slug>/",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "producten/",
        RedirectView.as_view(pattern_name="products:category_list"),
        name="product_detail",
    ),
    re_path(
        r"^(?P<category_slug>[\w\-\/]+)/producten/(?P<slug>[\w\-]+)/$",
        ProductDetailView.as_view(),
        name="category_product_detail",
    ),
    re_path(
        r"^(?P<slug>[\w\-\/]+)/$",
        CategoryDetailView.as_view(),
        name="category_detail",
    ),
    path("", CategoryListView.as_view(), name="category_list"),
]

src/open_inwoner/kvk/urls.py
from django.urls import path

from .views import CompanyBranchChoiceView

app_name = "kvk"

urlpatterns = [
    path("branches/", CompanyBranchChoiceView.as_view(), name="branches"),
]

src/open_inwoner/search/urls.py
from django.urls import path

from .views import SearchView

app_name = "search"
urlpatterns = [
    path("search/", SearchView.as_view(), name="search"),
]

src/open_inwoner/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views.generic import RedirectView, TemplateView

from maykin_2fa import monkeypatch_admin
from maykin_2fa.urls import urlpatterns, webauthn_urlpatterns
from mozilla_django_oidc_db.views import AdminLoginFailure

from digid_eherkenning_oidc_generics.views import OIDCFailureView
from open_inwoner.accounts.forms import CustomRegistrationForm
from open_inwoner.accounts.views import (
    AddPhoneNumberWizardView,
    CustomDigiDAssertionConsumerServiceMockView,
    CustomDigiDAssertionConsumerServiceView,
    CustomeHerkenningAssertionConsumerServiceMockView,
    CustomeHerkenningAssertionConsumerServiceView,
    CustomLoginView,
    CustomRegistrationView,
    LogPasswordChangeView,
    LogPasswordResetConfirmView,
    LogPasswordResetView,
    PasswordResetView,
    ResendTokenView,
    VerifyTokenView,
)
from open_inwoner.openklant.views.contactform import ContactFormView
from open_inwoner.pdc.views import FAQView

handler500 = "open_inwoner.utils.views.server_error"
admin.site.enable_nav_sidebar = False
admin.site.site_header = "Open Inwoner beheeromgeving"
admin.site.site_title = "Open Inwoner beheeromgeving"
admin.site.index_title = "Welkom op de OpenInwoner beheeromgeving"

monkeypatch_admin()

urlpatterns = [
    path(
        "admin/password_reset/",
        PasswordResetView.as_view(),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("admin/", include((urlpatterns, "maykin_2fa"))),
    path("admin/", include((webauthn_urlpatterns, "two_factor"))),
    path("admin/login/failure/", AdminLoginFailure.as_view(), name="admin-oidc-error"),
    path("admin/", admin.site.urls),
    path("csp/", include("cspreports.urls")),
    path("ckeditor/", include("open_inwoner.ckeditor5.urls")),
    # Simply show the master template.
    path(
        "accounts/register/",
        CustomRegistrationView.as_view(form_class=CustomRegistrationForm),
        name="django_registration_register",
    ),
    path(
        "accounts/password_change/",
        LogPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password_reset/",
        LogPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        LogPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("accounts/login/", CustomLoginView.as_view(), name="login"),
    path("accounts/verify/", VerifyTokenView.as_view(), name="verify_token"),
    path("accounts/resend-token/", ResendTokenView.as_view(), name="resend_token"),
    path(
        "accounts/add_phone_number/",
        AddPhoneNumberWizardView.as_view(),
        name="add_phone_number",
    ),
    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/", include("open_inwoner.api.urls", namespace="api")),
    path(
        "api/openzaak/",
        include("open_inwoner.openzaak.api.urls", namespace="openzaak_api"),
    ),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # Views
    path("accounts/", include("open_inwoner.accounts.urls", namespace="accounts")),
    path("pages/", include("django.contrib.flatpages.urls"), name="flatpages"),
    path("mail-editor/", include("mail_editor.urls", namespace="mail_editor")),
    path(
        "sessions/",
        include("open_inwoner.extended_sessions.urls", namespace="sessions"),
    ),
    path("contactformulier/", ContactFormView.as_view(), name="contactform"),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path(
        "digid-oidc/",
        include(
            "digid_eherkenning_oidc_generics.digid_urls",
        ),
    ),
    path(
        "eherkenning-oidc/",
        include(
            "digid_eherkenning_oidc_generics.eherkenning_urls",
        ),
    ),
    path("login/failure/", OIDCFailureView.as_view(), name="oidc-error"),
    path("faq/", FAQView.as_view(), name="general_faq"),
    path("yubin/", include("django_yubin.urls")),
    path("apimock/", include("open_inwoner.apimock.urls")),
    path("kvk/", include("open_inwoner.kvk.urls")),
    # TODO move search to products cms app?
    path("", include("open_inwoner.search.urls", namespace="search")),
    re_path(r"^", include("cms.urls")),
]

# NOTE: The staticfiles_urlpatterns also discovers static files (ie. no need to run collectstatic). Both the static
# folder and the media folder are only served via Django if DEBUG = True.
urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

urlpatterns = [
    path("metadata/", include("digid_eherkenning.metadata_urls"))
] + urlpatterns
if "digid_eherkenning.backends.DigiDBackend" in settings.AUTHENTICATION_BACKENDS:
    urlpatterns = [
        path(
            "digid/acs/",
            CustomDigiDAssertionConsumerServiceView.as_view(),
            name="acs",
        ),
        path("digid/", include("digid_eherkenning.digid_urls")),
    ] + urlpatterns
elif settings.DIGID_MOCK:
    urlpatterns = [
        path(
            "digid/acs/",
            CustomDigiDAssertionConsumerServiceMockView.as_view(),
            name="acs",
        ),
        path("digid/", include("digid_eherkenning.mock.digid_urls")),
        path("digid/idp/", include("digid_eherkenning.mock.idp.digid_urls")),
    ] + urlpatterns

if "eherkenning.backends.eHerkenningBackend" in settings.AUTHENTICATION_BACKENDS:
    urlpatterns = [
        path(
            "eherkenning/acs/",
            CustomeHerkenningAssertionConsumerServiceView.as_view(),
            name="eherkenning-acs",
        ),
        path("eherkenning/", include("digid_eherkenning.eherkenning_urls")),
    ] + urlpatterns
elif settings.EHERKENNING_MOCK:
    urlpatterns = [
        path(
            "eherkenning/acs/",
            CustomeHerkenningAssertionConsumerServiceMockView.as_view(),
            name="eherkenning-acs",
        ),
        path("eherkenning/", include("eherkenning.mock.eherkenning_urls")),
        path("eherkenning/idp/", include("eherkenning.mock.idp.eherkenning_urls")),
    ] + urlpatterns


if settings.DEBUG:
    urlpatterns = [
        # provide default styling template
        path(
            "style-demo/",
            TemplateView.as_view(template_name="components/Typography/StyleDemo.html"),
        ),
        # fix annoying favicon http error
        path("favicon.ico", RedirectView.as_view(url="/static/ico/favicon.png")),
    ] + urlpatterns

    if apps.is_installed("debug_toolbar"):
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns

if apps.is_installed("silk"):
    urlpatterns.insert(0, path(r"silk/", include("silk.urls", namespace="silk")))

src/open_inwoner/cms/banner/models.py
import os

from django.db import models
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin
from filer.fields.image import FilerImageField


class BannerImage(CMSPlugin):
    image = FilerImageField(
        verbose_name=_("Banner image"),
        on_delete=models.PROTECT,
        help_text=_("Banner image"),
    )
    image_height = models.PositiveIntegerField(
        verbose_name=_("Custom image height"),
        blank=True,
        null=True,
        help_text=_(
            "The image custom height as number in pixels. "
            'Example: "720" and not "720px".'
            "Leave this field empty if you want the original height of the image to be applied."
        ),
    )

    def __str__(self):
        return os.path.basename(self.image.file.name)


class BannerText(CMSPlugin):
    title = models.CharField(
        _("Title"),
        max_length=250,
        help_text=_("The title of the text block"),
    )
    description = models.TextField(
        verbose_name=_("Description"),
        null=True,
        blank=True,
        help_text=_("The description of the text block"),
    )

    def __str__(self):
        return self.title

src/open_inwoner/cms/extensions/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from cms.extensions import PageExtension
from cms.extensions.extension_pool import extension_pool

from open_inwoner.cms.extensions.constants import Icons, IndicatorChoices


class CommonExtension(PageExtension):
    requires_auth = models.BooleanField(
        _("Requires authentication"),
        default=False,
        help_text=_("Deze pagina vereist een account"),
    )
    requires_auth_bsn_or_kvk = models.BooleanField(
        _("Requires DigiD/eHerkenning authentication"),
        default=False,
        help_text=_(
            "Deze pagina vereist een account met een Digid BSN of eHerkenning KvK"
        ),
    )
    menu_indicator = models.CharField(
        _("Indicator"),
        max_length=32,
        choices=IndicatorChoices.choices,
        blank=True,
        help_text=_("Toon een counter naast het label"),
    )
    menu_icon = models.CharField(
        _("Icon"),
        max_length=32,
        choices=Icons.choices,
        blank=True,
        help_text=_("Icon in het menu"),
    )

    def __str__(self):
        return str(self.get_page())

    def save(self, *args, **kwargs):
        if self.requires_auth_bsn_or_kvk:
            self.requires_auth = True
        super().save(*args, **kwargs)


extension_pool.register(CommonExtension)

src/open_inwoner/cms/plugins/models/userfeed.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin


class UserFeed(CMSPlugin):
    title = models.CharField(
        _("Title"),
        max_length=250,
        help_text=_("The title of the plugin block"),
        default=_("Openstaande acties"),
    )

    def __str__(self):
        return self.title or super().__str__()

src/open_inwoner/cms/plugins/models/videoplayer.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from cms.models import CMSPlugin

from open_inwoner.media.models import Video


class VideoPlayer(CMSPlugin):
    video = models.ForeignKey(
        Video,
        help_text=_("The video from the catalog."),
        on_delete=models.PROTECT,
    )

    def __str__(self):
        if self.video_id:
            return str(self.video)
        else:
            return super().__str__()

src/open_inwoner/custom_csp/models.py
from collections import defaultdict

from django.db import models
from django.utils.translation import gettext_lazy as _

from .constants import CSPDirective


class CSPSettingQuerySet(models.QuerySet):
    def as_dict(self):
        ret = defaultdict(set)
        for directive, value in self.values_list("directive", "value"):
            ret[directive].add(value)
        return {k: list(v) for k, v in ret.items()}


class CSPSetting(models.Model):
    directive = models.CharField(
        _("directive"),
        max_length=64,
        help_text=_("CSP header directive"),
        choices=CSPDirective.choices,
    )
    value = models.CharField(
        _("value"),
        max_length=128,
        help_text=_("CSP header value"),
    )

    objects = CSPSettingQuerySet.as_manager()

    class Meta:
        ordering = ("directive", "value")

    def __str__(self):
        return f"{self.directive} '{self.value}'"

src/open_inwoner/pdc/models/faq.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import CheckConstraint, Q
from django.utils.translation import ugettext_lazy as _

from ordered_model.models import OrderedModel

from open_inwoner.pdc.managers import QuestionQueryset


class Question(OrderedModel):
    category = models.ForeignKey(
        "pdc.Category",
        verbose_name=_("Category"),
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    product = models.ForeignKey(
        "pdc.Product",
        verbose_name=_("Product"),
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    question = models.CharField(verbose_name=_("Vraag"), max_length=250)
    answer = models.TextField(verbose_name=_("Antwoord"))

    order_with_respect_to = "category"

    objects = QuestionQueryset.as_manager()

    class Meta(OrderedModel.Meta):
        verbose_name = _("Vraag")
        verbose_name_plural = _("FAQ vragen")
        ordering = ("category", "order")
        constraints = [
            CheckConstraint(
                check=Q(category__isnull=True) | Q(product__isnull=True),
                name="category_or_product_null",
            ),
        ]

    def clean(self):
        super().clean()
        if self.category and self.product:
            msg = _("A question cannot have both a category and a product")
            raise ValidationError({"category": msg, "product": msg})

    def __str__(self):
        return self.question

src/open_inwoner/pdc/models/neighbourhood.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Neighbourhood(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=100,
        unique=True,
        help_text=_("Neighbourhood name"),
    )

    class Meta:
        verbose_name = _("Neighbourhood")
        verbose_name_plural = _("Neighbourhoods")

    def __str__(self):
        return self.name

src/open_inwoner/templates/pages/product/detail.html
{% extends 'master.html' %}
{% load i18n l10n button_tags faq_tags file_tags grid_tags icon_tags link_tags map_tags notification_tags utils render_tags anchor_menu_tags product_tags string_tags %}

{% block header_image %}
{% if object.image %}
    <aside class="banner" aria-hidden="true">
        <img class="main-image main-image--start-after" src="{{ object.image.url }}" alt="">
    </aside>
{% endif %}
{% endblock header_image %}

{% block sidebar_content %}
    {% anchor_menu anchors=anchors desktop=True %}
        {% if not product.has_cta_tag %}
            {% if product.form %}
                <li class="anchor-menu__list-item">
                    {% button href=product.form_link size="big" text=_("Aanvraag starten") primary=True icon="arrow_forward" icon_position="before" %}
                </li>
            {% elif product.link %}
                <li class="anchor-menu__list-item">
                    {% button href=product.link size="big" text=_("Aanvraag starten") primary=True icon="arrow_forward" icon_position="before" %}
                </li>
            {% endif %}
        {% endif %}
    {% endanchor_menu %}
{% endblock sidebar_content %}

{% block content %}
    <h1 class="utrecht-heading-1" id="title">
    {{ object.name }}
        {% if request.user.is_staff %}
            {% button icon="edit" text=_("Bewerken in de Admin") hide_text=True href="admin:pdc_product_change" object_id=object.pk %}
        {% endif %}
    </h1>
    {% include "components/Tag/Tag.html" with tags=object.tags.all only %}
    <p class="p p-summary">{{ object.summary }}</p>

    {# Collapsable content #}
    <div class="readmore">
        {% if object.content_is_collapsable %}
            <a class="readmore__toggle button button--textless button--icon button--icon-after button--secondary button--transparent" href="#readmore__content" title="{% trans 'Click here in order to show extra content' %}" aria-label="{% trans 'Click here for more information' %}" aria-expanded="false">
                {% icon icon="expand_more" icon_position="after" icon_outlined=True %}
                <span class="readmore__button-text">{% trans "Click here for more information" %}</span>
                <span class="readmore__button-text--hidden">{% trans "Show less information" %}</span>
            </a>
        {% endif %}
        <div class="readmore__content" id="readmore__content" data-toggle-readmore="{{ readmore|lower }}">
            <div class="readmore__inner-content {% if object.content_is_collapsable %}readmore__content--hidden{% endif %}">
                {{ object|product_ckeditor_content|safe }}
            </div>
        </div>
    </div>

    {% if object.video %}
        {# duck-type the fact the videoplayer plugin also uses .video for the Video #}
        {% include "cms/plugins/videoplayer/videoplayer.html" with instance=object %}
    {% endif %}

    {% if object.question_set.exists or object.files.exists or object.conditions.exists or object.locations.exists or product_links.exists or object.related_products.published.exists or object.contacts.exists %}
        <hr class="divider">
    {% endif %}

    <div class="product-info">
        {% if object.question_set.exists %}
            {% faq object.question_set.all %}
        {% endif %}

        {% if object.files.exists %}
            {% file_list files=object.files.all title=_("Bestanden") %}
        {% endif %}

        {# Conditions #}
        {% if object.conditions.exists %}
            {% render_grid %}
                {% render_column span=6 compact=True %}
                    <h3 class="h3">{% trans "U komt in aanmerking" %}</h3>
                    {% include "components/Condition/ConditionList.html" with conditions=object.conditions.all only %}
                {% endrender_column %}

                {% render_column start=7 span=6 compact=True %}
                    <h3 class="h3">{% trans "U komt niet in aanmerking" %}</h3>
                    {% include "components/Condition/ConditionList.html" with conditions=object.conditions.all negative=True only %}
                {% endrender_column %}
            {% endrender_grid %}
        {% endif %}

        {# Locations #}
        {% if object.locations.exists %}
            {% with centroid=object.locations.get_centroid %}
                {% map centroid.lat centroid.lng id="locations" title=_('Locaties') geojson_feature_collection=object.locations.get_geojson_feature_collection %}
            {% endwith %}

            {% include "components/Card/CardContainer.html" with locations=object.locations.all columns=3 only %}
        {% endif %}

        {% render_grid %}
            {% render_column span=5 %}
                {# Links. #}
                {% if product_links.exists %}
                    <nav class="link-list" aria-label="{% trans "links" %}">
                        <h3 class="h3" id="links">{% trans "Links" %}</h3>
                        <ul class="link-list__list">
                            {% for link in product_links %}
                                <li class="link-list__list-item link-list__list-item--wrap">
                                    {% link href=link.url secondary=True text=link.name %}
                                </li>
                            {% endfor %}
                        </ul>
                    </nav>
                {% endif %}
            {% endrender_column %}

            {% render_column start=related_products_start span=4 compact=True %}
                {# Related products. #}
                {% if object.related_products.published.exists %}
                    <nav class="link-list" aria-label="{% trans "Gerelateerde links" %}">
                        <h3 class="h3" id="see">{% trans "Zie ook" %}</h3>
                        <ul class="link-list__list">
                            {% for related in object.related_products.published %}
                                <li class="link-list__list-item link-list__list-item--wrap">
                                    {% url 'products:product_detail' slug=related.slug as product_url %}
                                    {% link href=product_url text=related.name secondary=True %}
                                </li>
                            {% endfor %}
                        </ul>
                    </nav>
                {% endif %}
            {% endrender_column %}

            {% render_column span=9 %}
                {% if object.contacts.exists %}
                    <div class="contact-block">
                        <h3 class="h3" id="contact">{% trans 'Contact' %}</h3>

                        {% for contact in object.contacts.all %}
                            {% render_grid compact=True %}
                                {% render_column span=12 %}
                                    <h4 class="h4">{{ contact.first_name }} {{ contact.last_name }}</h4>
                                {% endrender_column %}

                                {% if contact.phonenumber %}
                                    {% render_column span=6 %}
                                        <span class="p">{{ contact.role|default:_('Telefoonnummer') }}</span>
                                    {% endrender_column %}

                                    {% render_column start=7 span=6 %}
                                        {% link href='tel:'|add:contact.phonenumber text=contact.phonenumber secondary=True %}
                                    {% endrender_column %}
                                {% endif %}

                                {% if contact.email %}
                                    {% render_column span=6 %}
                                        <p class="p">{{ contact.organization|default:_('E-mail')}}</p>
                                    {% endrender_column %}

                                    {% render_column start=7 span=6 %}
                                        {% link href='mailto:'|add:contact.email text=contact.email secondary=True %}
                                    {% endrender_column %}
                                {% endif %}
                            {% endrender_grid %}
                        {% endfor %}
                    </div>
                {% endif %}
            {% endrender_column %}
        {% endrender_grid %}

        {% if display_social %}
            <nav class="sharing-list" aria-label="{% trans "Deel dit artikel" %}">
                <h3 class="h3" id="sharing">{% trans "Deel dit artikel" %}</h3>
                {% with request.build_absolute_uri as page_url %}
                    {% include "components/ShareButton/ShareButton.html" with platform="facebook" platform_verbose="Facebook" text_to_share=page_url %}
                    {% include "components/ShareButton/ShareButton.html" with platform="x-twitter" platform_verbose="X" text_to_share=page_url %}
                    {% include "components/ShareButton/ShareButton.html" with platform="whatsapp" platform_verbose="WhatsApp" text_to_share=page_url %}
                    {% include "components/ShareButton/ShareButton.html" with platform="linkedin" platform_verbose="LinkedIn" text_to_share=page_url %}
                {% endwith %}
            </nav>
        {% endif %}

    </div>
{% endblock content %}

src/open_inwoner/templates/pages/product/finder.html
{% extends 'master.html' %}
{% load i18n l10n grid_tags link_tags form_tags button_tags product_tags utils %}

{% block content %}
    {% render_grid %}
        {% product_finder condition=condition form=form show_previous=show_previous conditions_done=conditions_done %}

        {% render_column start=7 span=6 compact=True %}
            <h1 class="h1" id="title">
                {% trans "Producten" %}
            </h1>

            <ul class="product-filter">
                {% for product in matched_products %}
                    <li class="product-filter__item">
                        {% link href=product.get_absolute_url text=product.name primary=True icon="arrow_forward" %}
                    </li>
		{% empty %}
		<li class="product-filter__item">
		  <p class="p">{% trans "Geen producten gevonden" %}</p>
		</li>
                {% endfor %}
            </ul>

            {% if possible_products %}
                <h1 class="h1" id="title">
                    {% trans "Mogelijke producten" %}
                </h1>

                <ul class="product-filter">
                    {% for product in possible_products %}
                        <li class="product-filter__item">
                            {% link href=product.get_absolute_url text=product.name primary=True icon="arrow_forward" %}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endrender_column %}
    {% endrender_grid %}
{% endblock content %}

src/open_inwoner/templates/pages/product/form.html
{% extends "pages/product/detail.html" %}
{% load openforms button_tags %}

{% block extra_css %}

    {{ block.super }}
    {% openforms_sdk_media %}

{% endblock %}

{% block sidebar_content %}
{% endblock %}

{% block content %}

    <h1 class="h1" id="title">
        {{ object.name }}
        {% if request.user.is_staff %}
            {% button icon="edit" text=_("Bewerken in de Admin") hide_text=True href="admin:pdc_product_change" object_id=object.pk %}
        {% endif %}
    </h1>
    {% include "components/Tag/Tag.html" with tags=object.tags.all only %}

    {% if object.form %}
        {% openforms_form object.form  csp_nonce=request.csp_nonce %}
    {% endif %}

{% endblock %}

src/open_inwoner/templates/pages/product/location_detail.html
{% extends 'master.html' %}
{% load i18n l10n grid_tags %}


{% block content %}
    <div class="location">
        <h1 class="h1">{{ object.name }}</h1>

        <div class="location__details">
            <div class="location__address">
                {% if object.address_line_1 %}
                    <p class="p">{{ object.address_line_1 }}</p>
                {% endif %}
                <p class="p">{{ object.address_line_2 }}</p>
            </div>
            <div class="location__contact">
                {% if object.phonenumber %}
                    <p class="p">{{ object.phonenumber }}</p>
                {% endif %}
                {% if object.email %}
                    <p class="p">{{ object.email }}</p>
                {% endif %}
            </div>
        </div>
    </div>

    {% if products %}
        {% include "components/Card/CardContainer.html" with products=products small=True only %}
    {% else %}
        {% trans "There are no products available at this location." %}
    {% endif %}
{% endblock content %}